# Generated by Django 4.1.6 on 2023-02-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('docuemnto', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('valor_sesion', models.IntegerField()),
                ('estado_sesion', models.CharField(max_length=40)),
            ],
        ),
    ]
